using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CSVMappingTemplate
{
    public static readonly string codeTemplate =
@"// This code automatically generated by CSVMappingMakerUtils
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class $CLASS_NAME$
{	
    public class CSVRow
    {
$TYPES$
    };
    
    public List<CSVRow> rows = new List<CSVRow>();
    
    public $CLASS_NAME$(TextAsset csv)
        : this(csv.text)
    {
        // empty    
    }
    
    public $CLASS_NAME$(string text)
    {
        rows.Clear();
        var parserData = SimpleCSVParser.Parser(text);
                
        // header(첫번째 행)를 제외하고 저장한다.
        for (int i = 1; i < parserData.Count; i++)
        {
            CSVRow row = new CSVRow();
$EXPORT_DATA$
            rows.Add(row);
        }
    }
}";
}
